spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: HOTEL-SERVICE
              uri: lb://HOTEL-SERVICE
              predicates:
#                - Path=/hotel/**
                - After=2026-03-12T04:25:03.966482460Z[GMT]        # This predicate is call after the specific zonedtime

            - id: RATING-SERVICE
              uri: lb://RATING-SERVICE
              predicates:
                - Path=/rating/**

            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/user/**


