spring.application.name=RATING-SERVICE
server.port=8083

spring.data.mongodb.uri=mongodb://localhost/microservice_prac1


eureka.client.service-url.defualtZone=http://localhost8761/eureka
eureka.instance.prefer-ip-address=true
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true